name: 'Setup and Build Environment'
description: 'Sets up environment and builds the Go application'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: src/server/go.mod
        cache: true
        cache-dependency-path: |
          src/server/go.sum
          src/client/go.sum
          src/ci-runner/go.sum

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: 'v2.24.6'
